### PR TITLE
mamun's assignment

### PR DESCRIPTION
**Pull request by unusedvariable**
feat:
- add golang mem
- add goto meme
- git out

### CODE REVIEW

**Review by wicaksonowibowomr — COMMENTED** [review]
wow luar biasa mas mamun....

**Review by rdnuansa — CHANGES_REQUESTED** [review]
Boleh sekalian coba upload homework Bash Scripting ke sini mas Mamun.

**Comment by unusedvariable** [comment]
> Boleh sekalian coba upload homework Bash Scripting ke sini mas Mamun.

updated mas @rdnuansa

**Review by rdnuansa — APPROVED** [review]
LGTM.

**Pull request merged**
